Ternary operator
SebastianMestre/Jasper pull request #119
Opened 2020-09-04 20:48 UTC by lushoBarlett

Implements the ternary operator.

~Currently it breaks in the typechecker...~ The Address Sanitizer complains about an illegal access in `typecheck(CallExpression)`, but I can't seem to understand why. I checked if it was a parsing mistake where it thought it was a CallExpression instead of something else, but I figured this should not be the case. I need help to understand if I misused the type system or something.

2020-09-04 20:52 UTC, SebastianMestre requested changes

2020-09-04 20:52 UTC, SebastianMestre commented on src/typecheck.cpp
> +}
`ast->m_value_type` is never assigned

2020-09-04 22:05 UTC, lushoBarlett commented
Okay so, I was a little confused as to _why_ something like `i == 0` even worked... After seeing how the `TypedAST` completely ignored it. Then I remembered that every bin-op is translated into a native function, so then it hit me why the failure ocurrs in a `CallExpression`. It's the `+` *function* that's getting called.

I probably need to check out where in the codebase that transformation happens, because I don't remember.

2020-09-04 22:28 UTC, SebastianMestre commented
The code looks good to me, and the tests pass... I'm not quite clear on whether it works, though. Your PR description seems to imply it doesn't. Does it work?

2020-09-04 23:14 UTC, SebastianMestre commented
Ok that's all cleared up, then

2020-09-04 23:15 UTC, SebastianMestre approved these changes
I have no comments, good job

2020-09-05 00:01 UTC, lushoBarlett commented
Just to leave record, the code **works**. I just left the problem (and the discovery of the problem) as a reminder of what happened. Also I felt like dashing all of that text would look bad.

2020-09-05 00:02 UTC, merged