Type function metadata
SebastianMestre/Jasper pull request #132
Opened 2020-09-18 02:09 UTC by lushoBarlett

2020-09-18 14:52 UTC, lushoBarlett commented
I didn't forget, it's because I wanted to keep the diff short. Plus I wanted to go to sleep

2020-09-19 00:47 UTC, lushoBarlett commented
> Don't you think a hashtable from string to monotype would be more appropiate?

I do. This is just my way to get your feedback on stuff. I didn't have a clear idea of what needed to be done for this at all actually, so I just came up with something and made it into a draft. Now that you mention it, this is actually a nice idea, because name duplication would have resolved by now.

2020-09-19 01:48 UTC, lushoBarlett commented
It didn't fail on my machine. So it must have automatically included the string library. Huh.

2020-09-19 20:45 UTC, SebastianMestre commented
> ... Plus I wanted to go to sleep

very reasonable

2020-09-19 20:46 UTC, SebastianMestre commented on src/typesystem.hpp
>  };
we will need a few more of these later, but this looks good for now

2020-09-19 22:38 UTC, SebastianMestre commented
I'm done with ioi now :)

adding a 'dummy' flag is probably a good idea

2020-09-21 11:13 UTC, SebastianMestre requested changes

2020-09-21 11:13 UTC, SebastianMestre commented on src/typesystem.cpp
> +		assert(0 && "instantiating type function that could not be deduced");
Oh I hadn't noticed but, this check is wrong.

We should be able to create a term with a typefunc that isnt known. We just need to go back at the end and verify that we do eventually learn what it is.

2020-09-21 11:13 UTC, SebastianMestre commented on src/typesystem.cpp
> +		assert(0 && "instantiating type function that could not be deduced");
Of course, in those cases we can't check that the argument is right. That also has to be done after type checking.

2020-09-21 11:13 UTC, SebastianMestre commented on src/typesystem.hpp
> +using TypeFunctionStructure = std::unordered_map<std::string, MonoId>;
Hold off on the typedefs. They make code less readable

2020-09-21 11:13 UTC, SebastianMestre commented on src/typesystem.hpp
> +	bool is_dummy = false;
We should really use brace notation for default values. It's just more idiomatic

 ```c++
bool is_dummy { false };
```

2020-09-21 11:17 UTC, SebastianMestre commented on src/typesystem.cpp
> +		assert(0 && "instantiating type function that could not be deduced");
The same thing goes for dummies. It should be possible to instanciate one, but we should make sure that it eventually gets resolved.

2020-09-21 11:20 UTC, SebastianMestre commented on src/typesystem.hpp
> +using TypeFunctionStructure = std::unordered_map<std::string, MonoId>;
This is not always the case, but when there is a different name for every possible instanciation of `std::unordered_map` and `std::vector`, it hinders more than it helps

2020-09-21 19:11 UTC, SebastianMestre approved these changes
I think we already discussed these points more than once, but, this is not what I had in mind

 - builtins, structs/unions, and tuples have different data, so they should be in separate arrays
 - also, when we are given a typefunc variable, or a dummy, we don't know what the argument count should be, so we shouldn't check it 

You don't seem to wanna do it that way, so I'll just approve this, and do it later.

2020-09-22 03:32 UTC, lushoBarlett commented
It's not that I don't wanna do it that way. I don't remember much of what we discussed about the implementation of this. The type system side is still new to me so it's natural than I don't wanna add many new elements at once.

With that said please tell me if you don't like something (or you'd rather it be done differently) I appreciate the guidance. Also if you think a pr should be closed, that's fine as well.

I'll merge it, since you approved it, and then you can adapt the parts that don't work.

2020-09-22 03:34 UTC, merged